Un perceptron es una red neuronal con solo una neurona.

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def sigmoid_derivative(x):
  return x*(1-x)

In [ ]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],])
shape = training_inputs.shape

In [ ]:
training_outputs = np.array([[0,1,1]]).T

In [ ]:
synaptic_weights = np.random.randn(shape[1], 1) * np.sqrt(1/shape[1]) #mejora respecto al vídeo
synaptic_weights

array([[-1.2174142 ],
       [ 0.52305347],
       [-0.62361541]])

In [ ]:
for iteration in range(20000):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))
  error = training_outputs - outputs
  adjustments = error * sigmoid_derivative(outputs)
  synaptic_weights += np.dot(input_layer.T, adjustments)

print(synaptic_weights)
print(outputs)
print(np.abs(error))

[[ 9.66768147]
 [ 1.76340155]
 [-4.72359158]]
[[0.00880522]
 [0.99877973]
 [0.99292484]]
[[0.00880522]
 [0.00122027]
 [0.00707516]]


In [ ]:
test_inputs = np.array([[0,1,1]])
test_outputs = np.array([[0]]).T #como el primer elemeto es un 0, el output debe ser 0

In [ ]:
input_layer = test_inputs
outputs = sigmoid(np.dot(input_layer, synaptic_weights))
error = test_outputs - outputs
print(outputs)
print(np.abs(error))

[[0.04925711]]
[[0.04925711]]


Predice que debe ser 0, como esperábamos.